name: go-lint-test-vet.yml
permissions:
  contents: read
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main, devel ]
jobs:
  lint-test:
    name: Lint, Vet, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
      - name: Verify go.mod
        run: go mod tidy && git diff --exit-code go.mod go.sum
      - name: Check formatting
        run: |
          gofmt_out=$(gofmt -l .)
          if [ -n "$gofmt_out" ]; then
            echo "❌ The following files are not gofmt formatted:"
            echo "$gofmt_out"
            exit 1
          fi
          echo "✅ Code is properly formatted"
      - name: Run go vet
        run: go vet ./...

#      - name: Run staticcheck (advanced linter)
#        uses: dominikh/staticcheck-action@v1
#        with:
#          version: "2024.1.1"
#      - name: Run tests
#        run: go test ./... -v -race -coverprofile=coverage.out
